Update multiuser bundle to version 11
sumocoders/Framework pull request #242
Opened 2019-01-16 07:39 UTC by Senjutsuu

2019-01-17 07:59 UTC, StijnVrolijk requested changes

2019-01-17 07:59 UTC, StijnVrolijk commented on composer.json
> +        "sumocoders/framework-multi-user-bundle": "11.0.0",
Dit mag ook ^11.0.0 zijn, anders gaat hij nooit updaten naar nieuwe versies

2019-01-17 08:01 UTC, Senjutsuu commented on composer.json
> +        "sumocoders/framework-multi-user-bundle": "11.0.0",
Goed gezien !

2019-01-17 08:06 UTC, StijnVrolijk approved these changes

2019-02-01 08:33 UTC, ohvitorino commented
@Senjutsuu You can

2019-02-01 08:34 UTC, merged

2019-02-01 08:35 UTC, ohvitorino commented
@Senjutsuu can you make a release for this?